"""
Synthetic transaction event generator.

Generates raw transactions whose numeric features follow the real training data
distributions (loaded from app/data/distributions.json).

Two modes controlled by config.is_kafka_configured():
  - Kafka mode: publishes raw (unscored) transactions to Kafka; scoring happens
    in the Spark RTM streaming job, and scored results come back via the
    Lakebase poller in main.py.
  - Inline mode (no Kafka): scores via Model Serving in-process and publishes
    scored transactions to subscriber queues directly.
"""

import asyncio
import json
import logging
import math
import os
import random
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from . import config

log = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

# ── Transaction ID counter (incrementing integer from 10,000,000) ──

_TXN_ID_START = 10_000_000
_next_txn_id = _TXN_ID_START


def _next_id() -> int:
    global _next_txn_id
    tid = _next_txn_id
    _next_txn_id += 1
    return tid


def reset_id_counter() -> None:
    global _next_txn_id
    _next_txn_id = _TXN_ID_START

# ── Load distribution profile (generated by scripts/profile_training_data.py) ──

_profile: Optional[dict] = None
_customers: Optional[list[dict]] = None


def _load_profile() -> Optional[dict]:
    path = DATA_DIR / "distributions.json"
    if not path.exists():
        log.warning("distributions.json not found at %s -- using fallback random generation", path)
        return None
    with open(path) as f:
        data = json.load(f)
    log.info(
        "Loaded distribution profile (%s types x is_fraud buckets, %d country pairs)",
        len(data.get("numeric_profiles", {})),
        len(data.get("country_pairs", [])),
    )
    return data


def _load_customers() -> Optional[list[dict]]:
    path = DATA_DIR / "customers.json"
    if not path.exists():
        log.warning("customers.json not found at %s -- using random names", path)
        return None
    with open(path) as f:
        data = json.load(f)
    log.info("Loaded %d customers from %s", len(data), path)
    return data


def _ensure_loaded():
    global _profile, _customers
    if _profile is None:
        _profile = _load_profile()
    if _customers is None:
        _customers = _load_customers()


# ── Fraud injection rate (fraction of txns generated with fraud-like features) ──

FRAUD_INJECTION_RATE = float(os.getenv("FRAUD_INJECTION_RATE", "0.30"))

# ── Fallback constants (used when distributions.json is absent) ──

FALLBACK_TYPES = ["PAYMENT", "TRANSFER", "CASH_OUT", "CASH_IN", "DEBIT"]
FALLBACK_COUNTRIES = [
    ("Russian Federation", 30), ("Brazil", 12), ("Canada", 10), ("France", 10),
    ("Turkey", 8), ("Peru", 7), ("Qatar", 6), ("Réunion", 6),
    ("Palestinian Territory, Occupied", 5), ("Spain", 5), ("Nigeria", 5),
    ("Panama", 4), ("Cambodia", 4),
]
FALLBACK_NAMES_FIRST = [
    "James", "Emma", "Oliver", "Sophia", "William", "Ava", "Benjamin", "Isabella",
    "Lucas", "Mia", "Henry", "Charlotte", "Alexander", "Amelia", "Daniel", "Harper",
]
FALLBACK_NAMES_LAST = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
    "Rodriguez", "Martinez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Lee",
]


# ── Distribution-aware generation ──

def _gauss_clamped(mean: float, stddev: float, lo: float, hi: float) -> float:
    """Generate a gaussian sample clamped to [lo, hi]."""
    if stddev <= 0 or math.isnan(stddev):
        return mean
    for _ in range(20):
        val = random.gauss(mean, stddev)
        if lo <= val <= hi:
            return round(val, 2)
    return round(max(lo, min(hi, random.gauss(mean, stddev))), 2)


def _pick_type_weighted(profile: dict, intent_fraud: bool) -> str:
    """Pick a transaction type based on training frequency distribution.

    When intent_fraud is True, only pick from types that had fraud in the
    training data (i.e. types with a fraud_count > 0).
    """
    freq = profile.get("type_frequencies", {})
    if not freq:
        return random.choice(FALLBACK_TYPES)

    if intent_fraud:
        fraud_types = {t: v for t, v in freq.items() if v.get("fraud_count", 0) > 0}
        if fraud_types:
            types = list(fraud_types.keys())
            weights = [fraud_types[t]["fraud_count"] for t in types]
            return random.choices(types, weights=weights, k=1)[0]

    types = list(freq.keys())
    weights = [freq[t]["count"] for t in types]
    return random.choices(types, weights=weights, k=1)[0]


def _pick_country_pair(profile: dict, intent_fraud: bool) -> tuple[str, str]:
    """Pick a country pair weighted by training frequency."""
    pairs = profile.get("country_pairs", [])
    if not pairs:
        fb = [c for c, _ in FALLBACK_COUNTRIES]
        fw = [w for _, w in FALLBACK_COUNTRIES]
        return random.choices(fb, weights=fw, k=1)[0], random.choices(fb, weights=fw, k=1)[0]

    if intent_fraud:
        # Weight toward pairs with higher fraud rates
        weights = [max(p["fraud_count"], 1) for p in pairs]
    else:
        weights = [p["count"] for p in pairs]

    chosen = random.choices(pairs, weights=weights, k=1)[0]
    return chosen["countryOrig_name"], chosen["countryDest_name"]


def _generate_numeric_features(profile: dict, txn_type: str, intent_fraud: bool) -> dict:
    """Generate the 5 numeric model features from the profiled distribution.

    Maintains critical inter-feature correlations that the model relies on:
      - CASH_OUT fraud: diffOrig = -amount, diffDest = 0 (money vanishes)
      - TRANSFER fraud: oldBalanceDest = 0, newBalanceDest ≈ amount (empty account)
      - Legit: features generated independently from profile, diffOrig ≈ -amount
    """
    fraud_flag = 1 if intent_fraud else 0
    bucket_key = f"{txn_type}_{fraud_flag}"
    bucket = profile.get("numeric_profiles", {}).get(bucket_key)

    if bucket is None:
        alt_key = f"{txn_type}_{0}"
        bucket = profile.get("numeric_profiles", {}).get(alt_key)

    if bucket is None:
        amount = round(random.lognormvariate(4.0, 1.5), 2)
        return {
            "amount": min(amount, 500_000),
            "old_balance_dest": round(random.uniform(0, 200_000), 2),
            "new_balance_dest": round(random.uniform(0, 200_000), 2),
            "diff_orig": round(-amount, 2),
            "diff_dest": round(amount, 2),
        }

    def _feat(name: str) -> float:
        f = bucket.get(name, {})
        return _gauss_clamped(f.get("mean", 0), f.get("stddev", 1), f.get("min", 0), f.get("max", 1e8))

    amount = _feat("amount")

    if intent_fraud and txn_type == "CASH_OUT":
        # Fraud CASH_OUT: money leaves orig, dest balance unchanged
        diff_orig = round(-amount, 2)
        old_balance_dest = _feat("oldBalanceDest")
        diff_dest = 0.0
        new_balance_dest = old_balance_dest

    elif intent_fraud and txn_type == "TRANSFER":
        # Fraud TRANSFER: money goes to an empty destination account
        old_balance_dest = 0.0
        diff_dest = round(amount, 2)
        new_balance_dest = round(amount, 2)
        diff_orig = round(-amount, 2)

    else:
        # Legit transactions: generate from profiles, enforce diffOrig ≈ -amount
        old_balance_dest = _feat("oldBalanceDest")
        diff_dest = _feat("diffDest")
        new_balance_dest = round(old_balance_dest + diff_dest, 2)
        diff_orig = round(-amount + random.gauss(0, amount * 0.02), 2)

    return {
        "amount": amount,
        "old_balance_dest": old_balance_dest,
        "new_balance_dest": new_balance_dest,
        "diff_orig": diff_orig,
        "diff_dest": diff_dest,
    }


def _pick_customer(customers: Optional[list[dict]]) -> dict:
    """Pick a random real customer, or generate a fake one."""
    if customers:
        return random.choice(customers)
    return {
        "id": random.randint(10000, 99999),
        "firstname": random.choice(FALLBACK_NAMES_FIRST),
        "lastname": random.choice(FALLBACK_NAMES_LAST),
    }


# ── Public API ──

def _generate_raw_transaction() -> dict:
    """Generate a single synthetic transaction (unscored) following real distributions."""
    _ensure_loaded()

    intent_fraud = random.random() < FRAUD_INJECTION_RATE

    if _profile:
        txn_type = _pick_type_weighted(_profile, intent_fraud)
        country_orig, country_dest = _pick_country_pair(_profile, intent_fraud)
        numerics = _generate_numeric_features(_profile, txn_type, intent_fraud)
    else:
        txn_type = random.choice(FALLBACK_TYPES)
        fb_c = [c for c, _ in FALLBACK_COUNTRIES]
        fb_w = [w for _, w in FALLBACK_COUNTRIES]
        country_orig = random.choices(fb_c, weights=fb_w, k=1)[0]
        country_dest = random.choices(fb_c, weights=fb_w, k=1)[0]
        amount = round(min(random.lognormvariate(4.0, 1.5), 500_000), 2)
        numerics = {
            "amount": amount,
            "old_balance_dest": round(random.uniform(0, 200_000), 2),
            "new_balance_dest": round(random.uniform(0, 200_000), 2),
            "diff_orig": round(-amount, 2),
            "diff_dest": round(amount, 2),
        }

    customer = _pick_customer(_customers)

    # Derive display-only orig balance fields from diffOrig
    old_balance_orig = round(abs(random.gauss(50_000, 30_000)), 2)
    new_balance_orig = round(old_balance_orig + numerics["diff_orig"], 2)

    now = datetime.now(timezone.utc)

    return {
        "id": _next_id(),
        "timestamp": now.isoformat(),
        "type": txn_type,
        "amount": numerics["amount"],
        "customer_id": customer["id"],
        "firstname": customer["firstname"],
        "lastname": customer["lastname"],
        "country_orig": country_orig,
        "country_dest": country_dest,
        "old_balance_orig": old_balance_orig,
        "new_balance_orig": new_balance_orig,
        "old_balance_dest": numerics["old_balance_dest"],
        "new_balance_dest": numerics["new_balance_dest"],
        "diff_orig": numerics["diff_orig"],
        "diff_dest": numerics["diff_dest"],
    }


class EventGenerator:
    """Controls synthetic transaction generation as a background task.

    In Kafka mode, raw transactions are published to Kafka (no scoring).
    In inline mode, transactions are scored via Model Serving and published
    to subscriber queues for immediate SSE delivery.
    """

    def __init__(self):
        self.running = False
        self.tps: float = 1.0
        self.total_generated: int = 0
        self.kafka_mode: bool = config.is_kafka_configured()
        self._task: Optional[asyncio.Task] = None
        self._subscribers: list[asyncio.Queue] = []

    def subscribe(self) -> asyncio.Queue:
        q: asyncio.Queue = asyncio.Queue(maxsize=200)
        self._subscribers.append(q)
        return q

    def unsubscribe(self, q: asyncio.Queue):
        if q in self._subscribers:
            self._subscribers.remove(q)

    async def _publish(self, txn: dict):
        for q in self._subscribers:
            try:
                q.put_nowait(txn)
            except asyncio.QueueFull:
                pass

    async def publish_external(self, txn: dict):
        """Inject an externally-sourced event (e.g. from the Lakebase poller)."""
        await self._publish(txn)

    async def _run_kafka(self):
        """Kafka mode: generate raw transactions and produce to Kafka."""
        from . import kafka_producer

        log.info("Generator running in KAFKA mode (topic=%s)", config.KAFKA_TOPIC)
        while self.running:
            raw = _generate_raw_transaction()
            await asyncio.to_thread(kafka_producer.produce, raw)
            self.total_generated += 1
            if self.tps > 0:
                await asyncio.sleep(1.0 / self.tps)
            if self.total_generated % 50 == 0:
                await asyncio.to_thread(kafka_producer.flush, 2.0)

    async def _run_inline(self):
        """Inline mode: generate, score locally, publish to subscriber queues."""
        from .scorer import score_transaction

        log.info("Generator running in INLINE mode (no Kafka)")
        while self.running:
            raw = _generate_raw_transaction()
            scored = await asyncio.to_thread(score_transaction, raw)
            scored["scored_at"] = datetime.now(timezone.utc).isoformat()
            self.total_generated += 1
            await self._publish(scored)
            if self.tps > 0:
                await asyncio.sleep(1.0 / self.tps)

    def start(self):
        if not self.running:
            self.running = True
            loop = asyncio.get_event_loop()
            if self.kafka_mode:
                self._task = loop.create_task(self._run_kafka())
            else:
                self._task = loop.create_task(self._run_inline())

    def stop(self):
        self.running = False
        if self._task:
            self._task.cancel()
            self._task = None
        if self.kafka_mode:
            from . import kafka_producer
            kafka_producer.flush(2.0)

    def set_speed(self, tps: float):
        self.tps = max(0.1, min(tps, 50.0))

    def status(self) -> dict:
        return {
            "running": self.running,
            "tps": self.tps,
            "total_generated": self.total_generated,
            "kafka_mode": self.kafka_mode,
        }
